> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 456-115-780
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 127.0.0.1 - - [18/Feb/2019 11:09:43] "GET / HTTP/1.1" 302 -
> 127.0.0.1 - - [18/Feb/2019 11:09:43] "GET /monitoring/1 HTTP/1.1" 301 -
> 127.0.0.1 - - [18/Feb/2019 11:09:43] "GET /monitoring/1/ HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:09:45] "GET /static/css/bootstrap-responsive.css HTTP/1.1" 304 -
> 127.0.0.1 - - [18/Feb/2019 11:09:45] "GET /static/css/eyecon-datepicker.css HTTP/1.1" 304 -
> 127.0.0.1 - - [18/Feb/2019 11:09:45] "GET /static/images/loading.gif HTTP/1.1" 304 -
> 127.0.0.1 - - [18/Feb/2019 11:09:45] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 -
> 127.0.0.1 - - [18/Feb/2019 11:09:45] "GET /static/js/jquery.js HTTP/1.1" 304 -
> 127.0.0.1 - - [18/Feb/2019 11:09:45] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 -
> 127.0.0.1 - - [18/Feb/2019 11:09:46] "GET /static/js/eyecon-datepicker.js HTTP/1.1" 304 -
> 127.0.0.1 - - [18/Feb/2019 11:09:46] "GET /static/img/glyphicons-halflings.png HTTP/1.1" 304 -
> 127.0.0.1 - - [18/Feb/2019 11:09:46] "GET /static/favicon.ico HTTP/1.1" 304 -
> 127.0.0.1 - - [18/Feb/2019 11:09:46] "GET /static/images/bar.png HTTP/1.1" 304 -
> 127.0.0.1 - - [18/Feb/2019 11:09:50] "GET /records/1 HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:09:54] "GET /case/13/ HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:09:55] "GET /thumb/pic/38/ HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:06] "GET /case/14/ HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:07] "GET /thumb/pic/39/ HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:18] "POST /case/14/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 580, in case
>     detection.main(images, Image)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\detection.py", line 11, in main
>     print(x.imread)
> AttributeError: 'Image' object has no attribute 'imread'
> 127.0.0.1 - - [18/Feb/2019 11:12:18] "GET /case/14/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:18] "GET /case/14/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:18] "GET /case/14/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:19] "GET /case/14/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:19] "GET /case/14/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:19] "GET /case/14/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:39] "POST /case/14/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 580, in case
>     detection.main(images, Image)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\detection.py", line 11, in main
> 127.0.0.1 - - [18/Feb/2019 11:12:39] "GET /case/14/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
>     print(x.imread)
> AttributeError: 'Image' object has no attribute 'imread'
> 127.0.0.1 - - [18/Feb/2019 11:12:40] "GET /case/14/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:40] "GET /case/14/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:40] "GET /case/14/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:40] "GET /case/14/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Feb/2019 11:12:40] "GET /case/14/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
>  * Detected change in 'C:\\Users\\gherz-PC\\Desktop\\remidiv2\\serveus\\detection.py', reloading
