> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 456-115-780
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 127.0.0.1 - - [09/Dec/2018 23:10:05] "GET /detect/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
>     return func(*args, **kwargs)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 140, in detect
>     return render_template("detect.html")
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 135, in render_template
>     context, ctx.app)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 117, in _render
>     rv = template.render(context)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\detect.html", line 1, in top-level template code
>     {% extends "layout.html" %}
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\layout.html", line 25, in top-level template code
>     {{user.usertype.name}} <b>{{user.firstname}} {{user.lastname}}</b> ({{ user.username }})
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 430, in getattr
>     return getattr(obj, attribute)
> UndefinedError: 'user' is undefined
> 127.0.0.1 - - [09/Dec/2018 23:10:06] "GET /detect/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:06] "GET /detect/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:06] "GET /detect/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:07] "GET /detect/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:07] "GET /detect/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:07] "GET /detect/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:19] "GET /detect/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
> 127.0.0.1 - - [09/Dec/2018 23:10:19] "GET /detect/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
>     return func(*args, **kwargs)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 140, in detect
>     return render_template("detect.html")
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 135, in render_template
>     context, ctx.app)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 117, in _render
>     rv = template.render(context)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\detect.html", line 1, in top-level template code
>     {% extends "layout.html" %}
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\layout.html", line 25, in top-level template code
>     {{user.usertype.name}} <b>{{user.firstname}} {{user.lastname}}</b> ({{ user.username }})
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 430, in getattr
>     return getattr(obj, attribute)
> UndefinedError: 'user' is undefined
> 127.0.0.1 - - [09/Dec/2018 23:10:19] "GET /detect/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:19] "GET /detect/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:20] "GET /detect/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:20] "GET /detect/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:20] "GET /detect/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:23] "GET / HTTP/1.1" 302 -
> 127.0.0.1 - - [09/Dec/2018 23:10:23] "GET /monitoring/1/ HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:26] "GET /detect/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
> 127.0.0.1 - - [09/Dec/2018 23:10:26] "GET /detect/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
>     return func(*args, **kwargs)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 140, in detect
>     return render_template("detect.html")
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 135, in render_template
>     context, ctx.app)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\templating.py", line 117, in _render
>     rv = template.render(context)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\detect.html", line 1, in top-level template code
>     {% extends "layout.html" %}
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\templates\layout.html", line 25, in top-level template code
>     {{user.usertype.name}} <b>{{user.firstname}} {{user.lastname}}</b> ({{ user.username }})
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\jinja2\environment.py", line 430, in getattr
>     return getattr(obj, attribute)
> UndefinedError: 'user' is undefined
> 127.0.0.1 - - [09/Dec/2018 23:10:26] "GET /detect/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:26] "GET /detect/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:27] "GET /detect/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [09/Dec/2018 23:10:27] "GET /detect/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
>  * Detected change in 'C:\\Users\\gherz-PC\\Desktop\\remidiv2\\serveus\\views.py', reloading
