> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 220-276-153
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 192.168.137.240 - - [05/Feb/2019 16:27:28] "GET /case/10/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\Patricia Cajaljal\Desktop\remidiv3\serveus\views.py", line 622, in case
>     if current_user.usertype == get_microscopist():
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
>     return getattr(self._get_current_object(), name)
> AttributeError: 'AnonymousUserMixin' object has no attribute 'usertype'
> 192.168.137.240 - - [05/Feb/2019 16:27:28] "GET /case/10/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:27:29] "GET /case/10/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:27:29] "GET /case/10/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:27:29] "GET /case/10/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:27:29] "GET /case/10/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:27:29] "GET /case/10/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> C:\Users\Patricia Cajaljal\Desktop\remidiv3\serveus\views.py:84: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
>   return render_template("index.html",login_form = LoginForm(), recovery_form = RecoveryForm())
> C:\Users\Patricia Cajaljal\Desktop\remidiv3\serveus\views.py:84: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
>   return render_template("index.html",login_form = LoginForm(), recovery_form = RecoveryForm())
> 192.168.137.240 - - [05/Feb/2019 16:27:37] "GET / HTTP/1.1" 200 -
> C:\Users\Patricia Cajaljal\Desktop\remidiv3\serveus\views.py:825: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
>   form = LoginForm()
> 192.168.137.240 - - [05/Feb/2019 16:27:39] "POST /login/ HTTP/1.1" 302 -
> 192.168.137.240 - - [05/Feb/2019 16:27:39] "GET /records/1 HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:27:46] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:27:46] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:27:49] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:27:51] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:27:51] "POST /api/db/ HTTP/1.1" 200 -
