> Initialized logger
> /home/annemirasol/remidiv2/serveus/views.py:5: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
>   from flask.ext.login import login_user, current_user, LoginManager, logout_user, login_required
> /home/annemirasol/remidiv2/serveus/forms.py:2: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
>   from flask.ext.wtf import Form
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
>  * Restarting with stat
> Initialized logger
> /home/annemirasol/remidiv2/serveus/views.py:5: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
>   from flask.ext.login import login_user, current_user, LoginManager, logout_user, login_required
> /home/annemirasol/remidiv2/serveus/forms.py:2: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
>   from flask.ext.wtf import Form
>  * Debugger is active!
>  * Debugger PIN: 322-981-763
> /home/annemirasol/remidiv2/serveus/views.py:726: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
>   form = LoginForm()
> 127.0.0.1 - - [13/Jun/2018 14:51:52] "[32mPOST /login/ HTTP/1.1[0m" 302 -
> 127.0.0.1 - - [13/Jun/2018 14:51:52] "[32mGET /monitoring/1 HTTP/1.1[0m" 301 -
> 127.0.0.1 - - [13/Jun/2018 14:51:52] "[37mGET /monitoring/1/ HTTP/1.1[0m" 200 -
> /usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py:643: SAWarning: Can't resolve label reference '"case".date desc'; converting to text() (this warning may be suppressed after 10 occurrences)
>   util.ellipses_string(element.element))
> 127.0.0.1 - - [13/Jun/2018 14:53:32] "[37mGET /records/1?region_selection=17&province_selection=99&municipality_selection=1638 HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:53:52] "[37mGET /case/2/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:54:03] "[32mGET /pic/9 HTTP/1.1[0m" 301 -
> 127.0.0.1 - - [13/Jun/2018 14:54:03] "[37mGET /pic/9/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:54:12] "[37mGET /map/1 HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:55:18] "[37mGET /timeline/1 HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:58:45] "[37mGET /records/1 HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:58:47] "[37mGET /case/1/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:58:47] "[32mGET /thumb/pic/1 HTTP/1.1[0m" 301 -
> 127.0.0.1 - - [13/Jun/2018 14:58:47] "[32mGET /thumb/pic/2 HTTP/1.1[0m" 301 -
> Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
> Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
> 127.0.0.1 - - [13/Jun/2018 14:58:47] "[37mGET /thumb/pic/1/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:58:47] "[37mGET /thumb/pic/2/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:58:53] "[37mPOST /case/1/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:59:31] "[32mGET /pic/1 HTTP/1.1[0m" 301 -
> 127.0.0.1 - - [13/Jun/2018 14:59:31] "[37mGET /pic/1/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:59:38] "[37mGET /pic/1/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:59:48] "[32mGET /pic/2 HTTP/1.1[0m" 301 -
> 127.0.0.1 - - [13/Jun/2018 14:59:48] "[37mGET /pic/1/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 14:59:48] "[37mGET /pic/2/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 15:14:35] "[37mGET /case/2/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 15:14:35] "[37mGET /thumb/pic/9/ HTTP/1.1[0m" 200 -
> Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
> 127.0.0.1 - - [13/Jun/2018 15:15:34] "[37mGET /case/3/ HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [13/Jun/2018 15:15:34] "[37mGET /thumb/pic/17/ HTTP/1.1[0m" 200 -
> Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
